### ISSUE TITLE
Can't rechachrge or dye pet castle

### ISSUE THREAD

**Issue by Virulent16** [TrueUO/TrueUO#1028]
The pet castle is supposed to be able to be dyed, and be recharged with Hitching Rope. Cannot do either. Tested on fresh server.
![PetCastle](https://user-images.githubusercontent.com/65615782/126874339-8865cc57-8fa7-4922-bed7-b6046757fde2.jpg)

**Comment by DocKnight86** [comment]
> The pet castle is supposed to be able to be dyed, and be recharged with Hitching Rope. Cannot do either. Tested on fresh server.
> ![PetCastle](https://user-images.githubusercontent.com/65615782/126874339-8865cc57-8fa7-4922-bed7-b6046757fde2.jpg)

For the dying - did you try to dye the deed first?

**Comment by Virulent16** [comment]
I did try to dye the deed first. Did not work

**Comment by TrueUO** [comment]
> I did try to dye the deed first. Did not work

What did you use? I used a dye tub and it worked fine. Dying the deed. Otherwise, if they are supposed to be dyable please include a link to where you are getting this information from.

**Comment by Virulent16** [comment]
> 
> 
> > I did try to dye the deed first. Did not work
> 
> What did you use? I used a dye tub and it worked fine. Dying the deed. Otherwise, if they are supposed to be dyable please include a link to where you are getting this information from.

Sorry! I should of clarified more. It cant be dyed with Tokuno dyes. I added a picture from OSI showing me dying my petcastle with Tokuno dyes, as well as link.

https://www.uo-cah.com/pub-110/first-look
![PetCastleDye](https://user-images.githubusercontent.com/65615782/126918389-f15511a0-cb55-4149-9f4e-2144781af483.jpg)
