### ISSUE TITLE
Pet Ability Bug

### ISSUE THREAD

**Issue by Argalep** [TrueUO/TrueUO#113]
pet ability work incorrectly on Life Leech and Steal Life

![sl](https://user-images.githubusercontent.com/17765272/81981256-b8252b00-9638-11ea-8a71-c1efe8486a61.PNG)

![ll](https://user-images.githubusercontent.com/17765272/81981258-b8bdc180-9638-11ea-849b-43a94ba060e2.PNG)

referance : https://www.uo-cah.com/foundations/pet-abilities

**Comment by kevin-10** [comment]
Do they have these for all the abilities?

**Comment by Argalep** [comment]
I am not sure. How can I test?
