### ISSUE TITLE
Moonstone Jewelry (Fezzik the Ogre Cook Loot)

### ISSUE THREAD

**Issue by Argalep** [TrueUO/TrueUO#147]
https://www.uoguide.com/Moonstone_Jewelry

Ask & Answer No. 19

2. Question from UO Stratics (Mentiras)

Moonstone Jewelery - Also submitted in Ask & Answer No. 13

Can a dev please make another statement on this drop? Specifically where does it actually come from now? Is it Fezzik the Chef or a cannibal mage or a chest in Fezzik's area? All over the previous? Has the drop % been altered because of the increase in difficulty of the target now? Thank you.

Misk:

Currently the only mob in game that can drop the moonstone jewelry is Fezzik the Ogre Cook. The chances for the jewelry to spawn is 1 in a 1000 and if you are lucky enough to get a drop they will spawn on the mobs corpse.

----

**Coloring condition**

Moonstone accessories have different shard colors.

It glowed blue in Trammel and red in Felucca, but remained gray in Malas, Tokuno, and Termur.

Trammel Color
![image](https://user-images.githubusercontent.com/17765272/83693976-ce068a00-a5ff-11ea-8183-2508304c233a.png)

Felucca Color
![image](https://user-images.githubusercontent.com/17765272/83693988-d19a1100-a5ff-11ea-8c8b-7300c1818917.png)

Malas - Termur - Tokuno Color
![image](https://user-images.githubusercontent.com/17765272/83693998-d5c62e80-a5ff-11ea-96d8-7aa1b1d86eae.png)

 **Law of change of color**

Also, in Tramel and Felucca, the lightness of the color gradually changed from low (black) to high (white) to low (black).

The transition time from the brightest state with high brightness to the darkest color was about 2 hours in UO.

![image](https://user-images.githubusercontent.com/17765272/83694147-1d4cba80-a600-11ea-9a86-d7a3047b9685.png)

![image](https://user-images.githubusercontent.com/17765272/83694154-2178d800-a600-11ea-8357-4f6c421a40be.png)

![image](https://user-images.githubusercontent.com/17765272/83694162-276eb900-a600-11ea-96c5-4de02edb716e.png)

![image](https://user-images.githubusercontent.com/17765272/83694171-2ccc0380-a600-11ea-8bda-3158a993cfe5.png)

![image](https://user-images.githubusercontent.com/17765272/83694177-2fc6f400-a600-11ea-981c-384afe3d9899.png)

**Moonstone Jewelry may spawn as a ring, earrings or bracelet and may be Imbued.**

![image](https://user-images.githubusercontent.com/17765272/83693678-3acd5480-a5ff-11ea-8278-5cad0826d42b.png)

**Comment by TrueUO** [comment]
Ha, very cool.

**Comment by TrueUO** [comment]
These items have been added.
