### ISSUE TITLE
Shadowguard The Orchard Apple Issue

### ISSUE THREAD

**Issue by Argalep** [TrueUO/TrueUO#195]
Pets can eat apples falling from the Shadowguard tree. Also, if the pets eats the apple, the creature does not spawn.

https://youtu.be/FZ7fOsbT630

**Comment by kevin-10** [comment]
Do you actually have to feed them to your pet?

**Comment by Argalep** [comment]
yes, osi is also available in this way

**Comment by kevin-10** [comment]
I will do a couple things here. First, I'll convert it to an apple. Next, I'm going to add a ItemSocket that will handle all decaying items. BaseDecayingItem will simply implement this item socket, and will use 1 static timer instead of each item having a timer. Thoughts?

**Comment by TrueUO** [comment]
Sounds great. A quick search of Heritage shows only 3 so I doubt it could ever bottle neck.
