### ISSUE TITLE
Anvil of Artifacts

### ISSUE THREAD

**Issue by Argalep** [TrueUO/TrueUO#226]
https://uo.com/wiki/ultima-online-wiki/items/ultima-store-inventory/anvil-of-artifacts

[AnvilofArtifacts.zip](https://github.com/TrueUO/TrueUO/files/4893508/AnvilofArtifacts.zip)

Missing - Only resists need to be applied.

**Comment by TrueUO** [comment]
We are holding off on this until we see how it is actually implemented. There have been rumors that it may not even get released.

**Comment by danielsheeper** [comment]
I checked this item directly on the official server.
![severlist](https://user-images.githubusercontent.com/22042552/89506068-7d7cfa00-d805-11ea-878a-5f1c5013123e.png)
![singleproduct](https://user-images.githubusercontent.com/22042552/89506053-77871900-d805-11ea-857b-098133881c41.png)
![uoshop2](https://user-images.githubusercontent.com/22042552/89506077-8241ae00-d805-11ea-9ccc-63cd6c69364f.png)
