### ISSUE TITLE
Possible Necro spells damage over time not revoking on death

### ISSUE THREAD

**Issue by adverserath** [TrueUO/TrueUO#644]
Fighting an paragon ancient lich with a cu, it became poisoned, possible through strange or poison strike and died. I ran out of the dungeon and rez'd on the way out (just as I went through the exit). When the outside of the dungeon loaded, it rez'd again, and was still taking damage every time the pet was resurected. Eventually the timer wore off, but the cu died about 7 times during the event.

**Comment by TrueUO** [comment]
https://github.com/TrueUO/TrueUO/blob/950bdcea1a4d82e9894f251c87266e9eba62bd96/Scripts/Spells/Necromancy/Strangle.cs#L177

**Comment by TrueUO** [comment]
So every 5 seconds it ticks. OnTick Strangle checks for if Alive. Is it possible each time between death / rez was under 5 seconds?

**Comment by kevin-10** [comment]
yea i think the timer should stop if you die. It currenlty does not.

**Comment by TrueUO** [comment]
https://trueuo.com/threads/strange-doubledeath.2692/
