### ISSUE TITLE
Barding timeouts distance should be by tile distance, not sqrt

### ISSUE THREAD

**Issue by adverserath** [TrueUO/TrueUO#766]
https://github.com/TrueUO/TrueUO/blob/8ed209dfcb41d0159e7872c0dcf3ff5002c5c392/Scripts/Skills/Discordance.cs#L97

The range check for discordance is based on tile distance:
    **(p1.X() >= (p2.X() - range))
    && (p1.X() <= (p2.X() + range))
    && (p1.Y() >= (p2.Y() - range))
    && (p1.Y() <= (p2.Y() + range));**

but the check for removing discord (GetBardDistance) is based on a sqrt distance, which tries to put a circular distance around the target.
    **xDelta = p1.X() - p2.X()
    yDelta = p1.Y() - p2.Y()
    Math.sqrt((xDelta*xDelta)+ (yDelta*yDelta)) < range;**

If you use barding on a target 10 tiles diagonally, the sqrt is then 14.14. So the discordance stops after 15 seconds.

When I have compared this with OSI test centre there is no sqrt implementation, its all direct tile distance.
As per the picture, with 100 discordance I get a bard range of 14. The effect still remains on the target when I am diagonal to the target 14 tiles, but the sqrt distance is 19.

![image](https://user-images.githubusercontent.com/37800482/114479989-85ddce00-9bf9-11eb-8a51-6365a22fa202.png)

**Comment by TrueUO** [comment]
Issue resolved.
