### ISSUE TITLE
OSI herding obsevations

### ISSUE THREAD

**Issue by adverserath** [TrueUO/TrueUO#767]
https://github.com/TrueUO/TrueUO/blob/8ed209dfcb41d0159e7872c0dcf3ff5002c5c392/Scripts/Items/Equipment/Weapons/ShepherdsCrook.cs#L72

- Skill check is made on the selection of the mobile, not the location to move to (Servuo checks on location selection)
- Mobiles follow you indefinitely, if they are 20 tiles away they are still moving towards you. Eventually they stop moving if you get too far ahead, but if you go back for them they will carry on following. (On servuo the following stops after about 8 tiles and you need to herd again)
- When you herd an animal onto another mobile their movement speed cant be outwalked. Its similar to a pet with high dex. (Servuo I can lose my flock in about 5 seconds of walking)
- Herding target distance is 14 tiles from player to creature (ServUo has it set to 10 tiles)

**Comment by TrueUO** [comment]
Resolved.
